#!/bin/sh

exec xautolock  -detectsleep -time 10 -locker "/home/msjche/.local/bin/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

exec xidlehook  --not-when-fullscreen --timer 1200 "systemctl suspend" - &

exec xset s 720 &
